my_string= input("Введите текст: ")
print("В вашем тексте", len(my_string), "символов(-а) (включая пробелы)")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ",""))
print(my_string[0])
print(my_string[-1])